//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace planning.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\sbouguerra\\Desktop\\personnel\\apps data\\personal planner\\1 categories.txt" +
            "")]
        public string categoriesFile {
            get {
                return ((string)(this["categoriesFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\sbouguerra\\Desktop\\personnel\\apps data\\personal planner\\4 one time free " +
            "events.txt")]
        public string OneFree {
            get {
                return ((string)(this["OneFree"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\sbouguerra\\Desktop\\personnel\\apps data\\personal planner\\5 recurrent free" +
            " events.txt")]
        public string RecFree {
            get {
                return ((string)(this["RecFree"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\sbouguerra\\Desktop\\personnel\\apps data\\personal planner\\2 one time fixed" +
            " events.txt")]
        public string OneFixed {
            get {
                return ((string)(this["OneFixed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\sbouguerra\\Desktop\\personnel\\apps data\\personal planner\\3 recurrent fixe" +
            "d events.txt")]
        public string RecFixed {
            get {
                return ((string)(this["RecFixed"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\sbouguerra\\Desktop\\personnel\\apps data\\personal planner\\plan.pdf")]
        public string outputpdf {
            get {
                return ((string)(this["outputpdf"]));
            }
            set {
                this["outputpdf"] = value;
            }
        }
    }
}
